<div class="box box-solid">
    <div class="box-header borda">
        <h3 class="titulo">Menu</h3>
    </div>
    <div class="box-body no-padding">
        <ul class="nav nav-pills nav-stacked">
            <li class="active"><a data-toggle="tab" href="#Pendentes">Pendentes</a></li>
            <li><a data-toggle="tab" href="#Ativas">Ativas</a></li>
            <li><a data-toggle="tab" href="#Finalizadas">Finalizadas</a></li>
            <li><a data-toggle="tab" href="#Rejeitadas">Rejeitadas</a></li>
<!--            <li><a >edit</a></li>-->
        </ul>
    </div>
</div>


