<div class="col-md-3">
    <div class="box box-solid">
        <div class="box-header borda">
            <h3 class="titulo">Menu</h3>
        </div>
        <div class="box-body no-padding">
            <ul class="nav nav-pills nav-stacked">
                <li class="active"><a data-toggle="tab"  href="#todos">Todos</a></li>
                <li><a data-toggle="tab"  href="#adicionar">Adicionar</a></li>
            </ul>
        </div>
    </div>
</div>