<div class="col-md-3">
    <div class="box box-solid">
        <div class="box-header borda">
            <h3 class="titulo">Pastas</h3>
        </div>
        <div class="box-body no-padding">
            <ul class="nav nav-pills nav-stacked">
                <li class="active"><a data-toggle="tab" href="#mensagens"><i class="glyphicon glyphicon-inbox"></i>
                        Entradas</a>
                </li>
                <li><a data-toggle="tab" href="#lixeira"><i class="glyphicon glyphicon-inbox"></i>
                        Lixeira</a>
                </li>
            </ul>
        </div>
    </div>
</div>