<div class="col-md-3">
    <div class="row">
        <div class="box box-solid">
            <div class="box-header borda">
                <h3 class="titulo">Menu</h3>
            </div>
            <div class="box-body no-padding">
                <ul class="nav nav-pills nav-stacked">
                    <li class="active"><a data-toggle="tab" href="#destaque">Editar Destaque</a></li>
                    <li><a data-toggle="tab" href="#carrossel">Editar Carrossel</a></li>
                    <li><a data-toggle="tab" href="#sobre">Editar Quem Somos</a></li>
                    <li><a data-toggle="tab" href="#fabricacao">Editar Como São Feitos</a></li>
                    <li><a data-toggle="tab" href="#contato">Editar Contato</a></li>
                    <li><a data-toggle="tab" href="#localizacao">Editar Localização</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>