<div class="col-md-3">
    <div class="box box-solid">
        <div class="box-header borda">
            <h3 class="titulo">Menu</h3>
        </div>
        <div class="box-body no-padding">
            <ul class="nav nav-pills nav-stacked">
                <li class="active"><a data-toggle="tab"  href="#prodMensal">Produção mensal</a></li> <!-- Gráfico de linha -->
                <li><a data-toggle="tab"  href="#prodEnc">Encomendas</a></li> <!-- Gráfico de linha -->
                <li><a data-toggle="tab"  href="#prodVend">Vendas</a></li> <!-- Gráfico de linha -->
                <li><a data-toggle="tab"  href="#despesas_receitas">Despesas/Receita</a></li>  <!-- Gráfico de barras -->
                <li><a data-toggle="tab"  href="#maisVendido">Encomendas populares</a></li> <!--Ver como faz-->
            </ul>
        </div>
    </div>
</div>



