<nav id="nav-config">
    <div id="voltar">
        <i class="glyphicon glyphicon-arrow-right"></i>
    </div>

    <div class="sidebar-header">
        <h4>Configurações</h4>
    </div>
    <div class="text-center">
        <h5 class="titulo">Temas</h5>

        <ul class="list-unstyled">
            <li>
                <a href="../Cookie/Tema/cookie.php?tema=TemaLaranja" data-toggle="tooltip" title="Tema Laranja">
                    <img src="../Imagens/Logo/TemaIcones/TemaLaranja.png">
                </a>
            </li>
            <li>
                <a href="../Cookie/Tema/cookie.php?tema=TemaAmarelo" data-toggle="tooltip" title="Tema Amarelo">
                    <img src="../Imagens/Logo/TemaIcones/TemaAmarelo.png">
                </a>
            </li>
            <li>
                <a href="../Cookie/Tema/cookie.php?tema=TemaVerde" data-toggle="tooltip" title="Tema Verde">
                    <img src="../Imagens/Logo/TemaIcones/TemaVerde.png">
                </a>
            </li>
            <li>
                <a href="../Cookie/Tema/cookie.php?tema=TemaVermelho" data-toggle="tooltip" title="Tema Vermelho">
                    <img src="../Imagens/Logo/TemaIcones/TemaVermelho.png">
                </a>
            </li>
        </ul>
    </div>
</nav>
