<footer id="footer" class="">
    <div id="footer-content" class="container-fluid content">
        <div class="col-sm-12 col-xs-12 text-center">
            <p class="esconder">Apoio</p>
            <a href="http://www.ifspcapivari.com.br/" target="_blank" class="grupo-img-item">
                <img src="../Imagens/Logo/logoif.png" class="img-responsive" id="img-footer">
            </a>
        </div>
        <div class="row ">
            <div class="socio-copyright">
                <p>Desenvolvido por<a href="#" target="_blank"> Mão na Massa</a> <i class="glyphicon glyphicon-heart"></i>. Todos os Direitos Reservados.</p>
            </div>
        </div>
    </div>
</footer>