<nav id="topnav" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">

            <a class="navbar-brand" href="#menu-toggle" id="menu-toggle"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></a>
            <a href="index.php" class="navbar-brand">Mão Na Massa</a>
        </div>
        <div class="menu">
            <ul class="nav navbar-nav ">
                <li class="m-l-10">
                    <a class="navbar-brand" href="#abrirConfg" id="abrirConfg"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>
