<form method="post" action=""class="">
    <div class="col-sm-12">
        <div class="box-header borda">
            <h3 class="titulo">Editar Destaque</h3>
        </div>
        <div class="col-sm-5 col-xs-12">
            <div class="img-Destaque">
                <img class="img-responsive" width="100%" alt="user" src="../Imagens/Destaque/trufa-morango.jpg" >
            </div>
        </div>
        <div class="col-sm-7 col-xs-12">
            <div class="form-group">
                <label for="text" class="col-md-12">Produto</label>
                <div class="col-md-12">
                    <select class="form-control" name="categoria" id="categoria">
                        <option>Selecione...</option>
                        <option>Trufa de Morango</option>
                        <option>Bolo de Abacaxi</option>
                        <option>Ovo de Páscoa tradicional</option>
                    </select>
                </div>
            </div>
            <div class="form-group text-right">
                <div class="col-sm-12">
                    <button class="btn btn-ativo">
                        <i class="glyphicon glyphicon-floppy-disk"></i>
                        Atualizar Destaque
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>